# .github/workflows/ci.yml
name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [main]
jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Ceedling
        run: sudo gem install ceedling --no-user-install
      - name: Clobber project
        run: ceedling clobber
      - name: Fetch dependencies
        run: ceedling dependencies:fetch
      - name: Build dependencies
        run: ceedling dependencies:make
      - name: Build laser
        run: ceedling release
  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run docker build
        run: docker build -f docker/Dockerfile .
